name: Publish VSCode Extension

on:
  push:
    branches: [ "main" ]


jobs:
  # Dependency Review Action
  #
  # This Action will scan dependency manifest files that change as part of a
  # Pull Request, surfacing known-vulnerable versions of the packages declared
  # or updated in the PR. Once installed, if the workflow run is marked as
  # required, PRs introducing known-vulnerable packages will be blocked from
  # merging.
  #
  # Source repository: https://github.com/actions/dependency-review-action
  # Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
  vsce-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'VSCE Install'
        run: npm install -g vsce
      - name: 'VSCE Publish'
        run: vsce publish -p ${{ secrets.vsceAccessToken }}

  # Build and Test
  #
  # Runs the build and test using Node 16.x and 18x.
  create-tag:
    runs-on: ubuntu-latest
    needs: vsce-publish
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: git tag -a v$(node scripts/print-version.js) -m "Release version $(node scripts/print-version.js)"
    - run: git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/TripleDotEngineering/tripledot-vscode-themes.git" v$(node scripts/print-version.js)


